name = "ToastyIsTheBest"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b18e3bbd50c861572d182196192019f5e28bed892ec5ce035ba3aeed0a0ace0b"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
