name = "ToastyIsTheBest"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0f9c870881042f7b455000dbea024abbc7f3864087b5d77520f21adac7cf9d7"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
