name = "ToastyIsTheBest"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1d819418349553d13c59950d9d222fb29ba4c17f7505473f7dfdb7e1ce0ee64"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
